//Richard Houth
//CS 356
package Assignment2.ui;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import Assignment2.model.Tweet;
import Assignment2.model.User;

/**
 *
 * @author richardhouth
 */
public class UserFrame extends javax.swing.JFrame {

    private User user;

    public UserFrame(User user) {
        this.user = user;

        initComponents();
        setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        userLabel.setText(user.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        model = new DefaultListModel();
        followingList = new javax.swing.JList<>();
        userLabel = new javax.swing.JLabel();
        followButton = new javax.swing.JButton();
        postMsgButton = new javax.swing.JButton();
        followingLabel = new javax.swing.JLabel();
        messageTextArea = new javax.swing.JScrollPane();
        tweetTextArea = new javax.swing.JTextArea();
        usernameTextField = new javax.swing.JTextField();
        lMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tweetModel = new DefaultListModel();
        tweetsList = new javax.swing.JList<>();
        tweetLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        followingList.setModel(model);
        for (User u : user.getFollowing()) {
            model.addElement(u.getName());
        }
        jScrollPane2.setViewportView(followingList);

        userLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userLabel.setText("User");

        followButton.setText("Follow");
        followButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followButtonActionPerformed(evt);
            }
        });

        postMsgButton.setText("Post Message");
        postMsgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postMsgButtonActionPerformed(evt);
            }
        });

        followingLabel.setText("Following");

        tweetTextArea.setColumns(20);
        tweetTextArea.setRows(5);
        messageTextArea.setViewportView(tweetTextArea);

        lMessage.setForeground(new java.awt.Color(255, 0, 51));

        tweetsList.setModel(tweetModel);
        for (Tweet t : user.getTweets()) {
            tweetModel.addElement(t.getMessage());
        }
        jScrollPane1.setViewportView(tweetsList);

        tweetLabel.setText("Tweets");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                        .addGap(22, 22, 22)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(18, 18, 18)
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                                .addComponent(usernameTextField)
                                                                                                .addComponent(followButton, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                                                                                .addComponent(followingLabel)
                                                                                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addContainerGap()
                                                                        .addComponent(messageTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(22, 22, 22)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(tweetLabel)
                                                                                        .addGap(239, 239, 239))
                                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(postMsgButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 9, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(lMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(userLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(followingLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(followButton)))
                                .addGap(18, 18, 18)
                                .addComponent(messageTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(postMsgButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tweetLabel)
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void followButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followButtonActionPerformed
        DefaultListModel model = (DefaultListModel) followingList.getModel();
        String username = usernameTextField.getText().trim();
        try {
            lMessage.setText("");
            if (!username.equals("")) {
                user.addFollowing(username);
                model.addElement(username);
            }
        } catch (Exception e) {
            lMessage.setText(e.getMessage());
        }
    }//GEN-LAST:event_followButtonActionPerformed

    private void postMsgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postMsgButtonActionPerformed
        DefaultListModel model = (DefaultListModel) tweetsList.getModel();
        String message = tweetTextArea.getText().trim();
        if (!message.equals("")) {
            Tweet tweet = user.postTweet(message);
            //TODO notify observers
            model.addElement(tweet.getMessage());
        }
    }//GEN-LAST:event_postMsgButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton followButton;
    private javax.swing.JLabel followingLabel;
    private javax.swing.JList<String> followingList;
    private DefaultListModel model;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lMessage;
    private javax.swing.JScrollPane messageTextArea;
    private javax.swing.JButton postMsgButton;
    private javax.swing.JLabel tweetLabel;
    private javax.swing.JTextArea tweetTextArea;
    private javax.swing.JList<String> tweetsList;
    private DefaultListModel tweetModel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables

}
